#ifndef _MY_EXTERNAL_
#define _MY_EXTERNAL_

typedef enum EXT_INT{
	EXT_INT_0,
	EXT_INT_1,
	EXT_INT_0_1
}EXT_INT;

typedef enum EXT_MODE{
	RISING_EDGE,
	FALLING_EDGE,
	LOW_LEVEL,
	EDGES
}EXT_MODE;

#define PORT_DIRECTION_INT0 0xFB
#define PORT_DIRECTION_INT1 0xF7
#define PORT_DIRECTION_INT 0xF3

#define SENCE_CON_INT0 0x03
#define SENCE_CON_INT1 0x0C
#define SENCE_CON_INT 0x0F

#define SENCE_CON_RISING_EDGE 0x0F
#define SENCE_CON_FALLING_EDGE 0x0A
#define SENCE_CON_RF_EDGE 0x05
#define SENCE_CON_LOW_LEVEL 0x00

#define ENABLE_INT0 0x01
#define ENABLE_INT1 0x02
#define ENABLE_INT 0x03

void setup_external_interrupt(EXT_INT no, EXT_MODE trigger_mode);

#endif //
